/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Quiz;

/**
 *
 * @author Lenovo
 */
public class formUtama extends javax.swing.JFrame {

    /**
     * Creates new form formUtama
     */
    public formUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuEntriDataMahasiswa22081012 = new javax.swing.JMenuItem();
        menuEntriDataMatakuliah22081012 = new javax.swing.JMenuItem();
        menuEntriDataKRS22081012 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuTampilDataMahasiswa22081012 = new javax.swing.JMenuItem();
        menuTampilDataMatakuliah22081012 = new javax.swing.JMenuItem();
        menuTampilDataKRS22081012 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuPencarianDataMahasiswa22081012 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Entri Data");

        menuEntriDataMahasiswa22081012.setText("Entri Data Mahasiswa");
        menuEntriDataMahasiswa22081012.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEntriDataMahasiswa22081012ActionPerformed(evt);
            }
        });
        jMenu1.add(menuEntriDataMahasiswa22081012);

        menuEntriDataMatakuliah22081012.setText("Entri Data Matakuliah");
        menuEntriDataMatakuliah22081012.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEntriDataMatakuliah22081012ActionPerformed(evt);
            }
        });
        jMenu1.add(menuEntriDataMatakuliah22081012);

        menuEntriDataKRS22081012.setText("Entri Data KRS");
        menuEntriDataKRS22081012.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEntriDataKRS22081012ActionPerformed(evt);
            }
        });
        jMenu1.add(menuEntriDataKRS22081012);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Tampil Data");

        menuTampilDataMahasiswa22081012.setText("Tampil Data Mahasiswa");
        menuTampilDataMahasiswa22081012.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTampilDataMahasiswa22081012ActionPerformed(evt);
            }
        });
        jMenu2.add(menuTampilDataMahasiswa22081012);

        menuTampilDataMatakuliah22081012.setText("Tampil Data Matakuliah");
        menuTampilDataMatakuliah22081012.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTampilDataMatakuliah22081012ActionPerformed(evt);
            }
        });
        jMenu2.add(menuTampilDataMatakuliah22081012);

        menuTampilDataKRS22081012.setText("Tampil Data KRS");
        menuTampilDataKRS22081012.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTampilDataKRS22081012ActionPerformed(evt);
            }
        });
        jMenu2.add(menuTampilDataKRS22081012);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Pencarian");

        menuPencarianDataMahasiswa22081012.setText("Pencarian Data Mahasiswa");
        menuPencarianDataMahasiswa22081012.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPencarianDataMahasiswa22081012ActionPerformed(evt);
            }
        });
        jMenu3.add(menuPencarianDataMahasiswa22081012);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 379, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuEntriDataKRS22081012ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEntriDataKRS22081012ActionPerformed
        // TODO add your handling code here:
        formEntriKrs entrikrs = new formEntriKrs();
        entrikrs.setVisible(true);
    }//GEN-LAST:event_menuEntriDataKRS22081012ActionPerformed

    private void menuEntriDataMahasiswa22081012ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEntriDataMahasiswa22081012ActionPerformed
        // TODO add your handling code here:
        formEntriMahasiswa entrimahasiswa = new formEntriMahasiswa();
        entrimahasiswa.setVisible(true);
    }//GEN-LAST:event_menuEntriDataMahasiswa22081012ActionPerformed

    private void menuEntriDataMatakuliah22081012ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEntriDataMatakuliah22081012ActionPerformed
        // TODO add your handling code here:
        formEntriMatakuliah entrimatakuliah = new formEntriMatakuliah();
        entrimatakuliah.setVisible(true);
    }//GEN-LAST:event_menuEntriDataMatakuliah22081012ActionPerformed

    private void menuTampilDataMahasiswa22081012ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTampilDataMahasiswa22081012ActionPerformed
        // TODO add your handling code here:
        formTampilMahasiswa tampilmahasiswa = new formTampilMahasiswa();
        tampilmahasiswa.setVisible(true);
    }//GEN-LAST:event_menuTampilDataMahasiswa22081012ActionPerformed

    private void menuTampilDataMatakuliah22081012ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTampilDataMatakuliah22081012ActionPerformed
        // TODO add your handling code here:
        formTampilMatakuliah tampilmatakuliah = new formTampilMatakuliah();
        tampilmatakuliah.setVisible(true);
    }//GEN-LAST:event_menuTampilDataMatakuliah22081012ActionPerformed

    private void menuTampilDataKRS22081012ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTampilDataKRS22081012ActionPerformed
        // TODO add your handling code here:
        formTampilKrs tampilkrs = new formTampilKrs();
        tampilkrs.setVisible(true);
    }//GEN-LAST:event_menuTampilDataKRS22081012ActionPerformed

    private void menuPencarianDataMahasiswa22081012ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPencarianDataMahasiswa22081012ActionPerformed
        // TODO add your handling code here:
        formCariMahasiswa carimahasiswa = new formCariMahasiswa();
        carimahasiswa.setVisible(true);
    }//GEN-LAST:event_menuPencarianDataMahasiswa22081012ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuEntriDataKRS22081012;
    private javax.swing.JMenuItem menuEntriDataMahasiswa22081012;
    private javax.swing.JMenuItem menuEntriDataMatakuliah22081012;
    private javax.swing.JMenuItem menuPencarianDataMahasiswa22081012;
    private javax.swing.JMenuItem menuTampilDataKRS22081012;
    private javax.swing.JMenuItem menuTampilDataMahasiswa22081012;
    private javax.swing.JMenuItem menuTampilDataMatakuliah22081012;
    // End of variables declaration//GEN-END:variables
}
